version: '3'

services:
  go-proxy-bingai:
    # 镜像名称
    image: adams549659584/go-proxy-bingai
    # 容器名称
    container_name: go-proxy-bingai  
    # 自启动
    restart: unless-stopped
    ports:
      - 8080:8080
    # environment:
    #   - Go_Proxy_BingAI_SOCKS_URL=192.168.0.88:1070
    #   - Go_Proxy_BingAI_SOCKS_USER=robrehao@dingtalk.com
    #   - Go_Proxy_BingAI_SOCKS_PWD=841103
    #   - Go_Proxy_BingAI_USER_TOKEN_1=1K4MdQuQOYR7h0sUP1TYY1ZycxPQpIcvBCJY-EXTeLW9RbePdPSRNCoA_DEwwMn5khwkkrxWdpTbGu7cosv0OVnOfcjYXf8kk4EcTqbGhn-JhmsAqwdE3S5h8fLkm9gsM1BPZKC7KUIqjABeQHChTvloUcvF0MMe2rxQWOzQiWo6zdPHuK1dE_3nzLOf58ZgStkdHbLS1lFk7pp_UtaSXs6MFnoxbbC5_pypIqqE_WOo
    #   - Go_Proxy_BingAI_USER_TOKEN_2=xxx
  
#   go-proxy-bingai:
#     # 镜像名称
#     image: adams549659584/go-proxy-bingai
#     # 容器名称
#     container_name: go-proxy-bingai
#     build:
#       context: ../
#       dockerfile: docker/Dockerfile      
#     # 自启动
#     restart: unless-stopped
#     # 加入指定网络
#     networks:
#       - MyNetwork    
#     ports:
#       - 8888:8080
#     environment:
#       - Go_Proxy_BingAI_SOCKS_URL=192.168.0.88:1070
#       # - Go_Proxy_BingAI_SOCKS_USER=robrehao@dingtalk.com
#       # - Go_Proxy_BingAI_SOCKS_PWD=841103        

# networks:
#   MyNetwork:
#     external: true

